image:
  file: Dockerfile
tasks:
- init: npm install
  command: npm start
ports:
- port: 3000
  onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
vscode:
  extensions:
    - edukera.archetype@0.38.0:34b46074dc387b4474aec36d202ee28b
    - baking-bad.michelson@0.1.0:0e45f95fc6b866c2888fe25844470b8c
